version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./config.json:/app/config.json

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  memcache:
    image: memcached:alpine
    ports:
      - "11211:11211"
